amcl:
  ros__parameters:
    use_sim_time: true
    base_frame_id: base_link
    odom_frame_id: odom
    global_frame_id: map
    scan_topic: scan
    save_pose_rate: 0.5

    robot_model_type: nav2_amcl::OmniMotionModel

    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2

    laser_model_type: likelihood_field
    laser_max_range: 10.0
    laser_min_range: 0.12
    laser_max_beams: 240

    min_particles: 500
    max_particles: 3000
    resample_interval: 1
    pf_err: 0.05
    pf_z: 0.99

    update_min_d: 0.2
    update_min_a: 0.2

    recovery_alpha_slow: 0.001
    recovery_alpha_fast: 0.1

    tf_broadcast: true

map_server:
  ros__parameters:
    use_sim_time: True
    frame_id: map

map_saver:
  ros__parameters:
    use_sim_time: True
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True
